apiVersion: v1
kind: Service
metadata:
  name: globomantics-website
  namespace: globomantics-wrong-service-label
spec:
  selector:
    app: globomantics-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: web
