apiVersion: v1
kind: Service
metadata:
  name: globomantics-website
spec:
  selector:
    app: globomantics-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: web
  type: ClusterIP