apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: globomantics-website
spec:
  to:
    kind: Service
    name: globomantics-website
  port:
    targetPort: web
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect