apiVersion: apps/v1
kind: Deployment
metadata:
  name: globomantics-website
  namespace: implement-hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globomantics-website
  template:
    metadata:
      labels:
        app: globomantics-website
    spec:
      containers:
        - name: globomantics-web
          image: ghcr.io/rummens/pluralsight-globomantics-website-with-db:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "200m"
              memory: "100Mi"

          env:
            # Required flags
            - name: DB_REQUIRED
              value: "false"
            - name: FLASK_DEBUG
              value: "true"
            - name: REQUEST_LOGGING
              value: "true"
            - name: STARTUP_DELAY
              value: "10"
