apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-secret
  namespace: broken-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-secret
  template:
    metadata:
      labels:
        app: demo-secret
    spec:
      containers:
        - name: app
          image: registry.access.redhat.com/ubi9/ubi-minimal
          command: ["/bin/sh", "-c"]
          args:
            - sleep 3600
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_password   # WRONG KEY